Repository diffCheckOrg/diffCheck, pull requests merged in 2024-07, with the labels that each got.

#35 FIX for Patch color convertion bug
  src/gh/components/DF_tester/code.py
  src/gh/diffCheck/diffCheck/df_cvt_bindings.py
  src/gh/examples/assembly_beam_system.ghx
Labels: patch

#36 Test suite structure
  CMakeLists.txt
  CONTRIBUTING.md
  cmake/__noenv__config.bat
  cmake/clean_config.bat
  cmake/config.bat
  cmake/external_tools.cmake
  src/diffCheckApp.cc
  tests/entryTest.cc
  tests/test_data/.gitkeep
  tests/unit_tests/DFPointCloudTest.cc
Labels: dev, patch

#40 Substractive registration refinement
  src/diffCheck/geometry/DFMesh.cc
  src/diffCheck/geometry/DFPointCloud.cc
  src/diffCheck/geometry/DFPointCloud.hh
  src/diffCheckApp.cc
  src/diffCheckBindings.cc
  src/gh/components/DF_joint_segmentator/code.py
  src/gh/components/DF_joint_segmentator/icon.png
  src/gh/components/DF_joint_segmentator/metadata.json
  src/gh/diffCheck/diffCheck/df_cvt_bindings.py
Labels: grasshopper, backend

#41 test suite framework 🧪
  .github/workflows/cpp-build.yml
  .github/workflows/pypi-build.yml
  .github/workflows/test-pass.yml
  CMakeLists.txt
  CONTRIBUTING.md
  README.md
  ScreenCamera_2024-06-30-00-00-53.json
  ScreenCamera_2024-06-30-11-58-46.json
  ScreenCapture_2024-06-30-00-00-53.png
  ScreenCapture_2024-06-30-11-58-46.png
  cmake/build.bat
  cmake/clean_config.bat
  cmake/config.bat
  cmake/options.cmake
  cmake/tests.cmake
  environment.yml
  src/diffCheck/IOManager.cc
  src/diffCheck/IOManager.hh
  src/diffCheckApp.cc
  src/gh/components/DF_tester/code.py
  src/gh/diffCheck/diffCheck/df_cvt_bindings.py
  tests/allCppTests.cc
  tests/integration_tests/ghcomponents_tests/.gitkeep
  tests/integration_tests/ghcomponents_tests/__init__.py
  tests/integration_tests/package_tests/.gitkeep
  tests/integration_tests/package_tests/__init__.py
  tests/integration_tests/pybinds_tests/__init__.py
  tests/integration_tests/pybinds_tests/test_pybind_dll_smoke.py
  tests/integration_tests/pybinds_tests/test_pybind_pyver.py
  tests/integration_tests/pybinds_tests/test_pybind_units.py
  tests/test_data/roof_quarter.ply
  tests/unit_tests/DFLog.cc
  tests/unit_tests/DFPointCloudTest.cc
Labels: test_suite
