Repository diffCheckOrg/diffCheck, pull requests merged in 2024-09, with the labels that each got.

#113 fix color issue
  src/gh/diffCheck/diffCheck/df_cvt_bindings.py
Labels: bug, backend

#99 ADD SOR method to DFPointCloud objects
  doc/gh_DFRemoveStatisticalOutliers.rst
  doc/gh_components.rst
  src/diffCheck/IOManager.cc
  src/diffCheck/IOManager.hh
  src/diffCheck/geometry/DFPointCloud.cc
  src/diffCheck/geometry/DFPointCloud.hh
  src/diffCheckBindings.cc
  src/gh/components/DF_remove_statistical_outliers/code.py
  src/gh/components/DF_remove_statistical_outliers/icon.png
  src/gh/components/DF_remove_statistical_outliers/metadata.json
  tests/integration_tests/pybinds_tests/test_pybind_units.py
  tests/test_data/test_pc_for_SOR_101pts_with_1_outlier.ply
  tests/unit_tests/DFPointCloudTest.cc
Labels: grasshopper, backend, PythonAPI, PyBind11

#108 component safety fixes
  src/gh/components/DF_CAD_segmentator/code.py
  src/gh/components/DF_CAD_segmentator/metadata.json
  src/gh/components/DF_cloud_cloud_distance/code.py
  src/gh/components/DF_cloud_mesh_distance/code.py
  src/gh/components/DF_cloud_normal_estimator/code.py
  src/gh/components/DF_cloud_size_downsample/code.py
  src/gh/components/DF_cloud_uniform_downsample/code.py
  src/gh/components/DF_cloud_voxel_downsample/code.py
  src/gh/components/DF_csv_exporter/metadata.json
  src/gh/components/DF_deconstruct_beam/code.py
  src/gh/components/DF_fast_global_registration/code.py
  src/gh/components/DF_icp_registration/code.py
  src/gh/components/DF_joint_segmentator/code.py
  src/gh/components/DF_mesh_to_cloud/code.py
  src/gh/components/DF_normal_segmentator/code.py
  src/gh/components/DF_normal_segmentator/metadata.json
  src/gh/components/DF_ransac_global_registration/code.py
  src/gh/components/DF_remove_beam/code.py
  src/gh/components/DF_visualization_settings/code.py
Labels: documentation, grasshopper

#117 per-joint segmentation works at joint face level
  src/diffCheck/segmentation/DFSegmentation.cc
  src/diffCheck/segmentation/DFSegmentation.hh
  src/diffCheckApp.cc
  src/gh/components/DF_CAD_segmentator/code.py
  src/gh/components/DF_joint_segmentator/code.py
  src/gh/components/DF_joint_segmentator/metadata.json
  src/gh/components/DF_mesh_to_cloud/code.py
Labels: patch, grasshopper, backend

#115 Enhancements error viz
  src/gh/components/DF_cloud_mesh_distance/code.py
  src/gh/components/DF_cloud_mesh_distance/metadata.json
  src/gh/components/DF_csv_exporter/code.py
  src/gh/components/DF_csv_exporter/metadata.json
  src/gh/components/DF_tester/metadata.json
  src/gh/components/DF_visualization/code.py
  src/gh/components/DF_visualization/metadata.json
  src/gh/components/DF_visualization_settings/code.py
  src/gh/components/DF_visualization_settings/metadata.json
  src/gh/diffCheck/diffCheck.egg-info/PKG-INFO
  src/gh/diffCheck/diffCheck/df_error_estimation.py
  src/gh/diffCheck/diffCheck/df_visualization.py
  src/gh/examples/error_viz_tester_components.ghx
Labels: grasshopper, PythonAPI

#128 tiny naming fix for CAD segmentator
  src/gh/components/DF_CAD_segmentator/code.py
Labels: bug, patch, grasshopper

#130 FIX to DFCloud2Mesh
  src/gh/components/DF_cloud_mesh_distance/code.py
  src/gh/components/DF_cloud_mesh_distance/metadata.json
Labels: grasshopper, cleaning
